import React, { useEffect, useState } from 'react'
import axios from 'axios';
import jwt_decode from "jwt-decode";
import LandingNavBar from '../Components/LandingNavbar';
import LoggedInNavbar from '../Components/LoggedInNavbar';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { CardActionArea, Grid } from '@mui/material';
import { Link, useNavigate } from 'react-router-dom';
import "./Background.css";


export const Home = () => {
  const [name, setName] = useState('');
  const [ispost, setpost] = useState([]);
  const navigate = useNavigate();
  useEffect(() => {
    refreshToken();
    viewPost();
    }, []);

    const refreshToken = async () => {
        try {
            const response = await axios.get('http://localhost:5000/token');
            const decoded = jwt_decode(response.data.accessToken);
            setName(decoded.name);
        } catch (error) {
            if (error.response) {
            }
        }
      }

      const viewPost = async() =>{
        try {
          axios.get(`http://localhost:5000/posts`)
          .then(res => { 
              setpost(res.data);
          })
        } catch (error) { throw error;}
      }

      const navbarDecider = () =>{
        if(name.length > 0) {
          return <LoggedInNavbar />
        }else{
          return <LandingNavBar />}
      }
  return (
    <>
        {navbarDecider()}
        <div className='gradient-custom-3'>
        <br/>
        <br/>
        <br/>
        <br/>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec posuere cursus faucibus. Ut rhoncus tincidunt ante sed auctor. Vestibulum scelerisque ipsum eu elit rutrum commodo. Maecenas eleifend felis et facilisis aliquam. Proin pellentesque elit euismod tellus pulvinar, ut consectetur lacus aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam mollis justo et nibh tempor porttitor. Duis consectetur, eros ut rhoncus imperdiet, tellus arcu efficitur magna, non iaculis eros nisi eget ipsum. In velit nulla, ultricies non mollis eget, auctor vulputate ligula. In commodo erat id felis interdum ullamcorper. Praesent gravida dui scelerisque sapien pulvinar ultricies. Ut vulputate ultricies massa, nec rutrum magna imperdiet non.

Etiam porta mauris sit amet ipsum lacinia elementum. Praesent feugiat dui fermentum elit posuere, vehicula laoreet ex fringilla. Donec tortor tortor, feugiat ut lobortis sed, pellentesque at augue. Nulla nisi massa, placerat in dictum et, pulvinar a dui. Nam rhoncus sem auctor nunc scelerisque tristique. Donec imperdiet tempor leo, sed dignissim odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse consequat tortor at ante sollicitudin, nec lacinia ante blandit.

Duis at ante tempor, mattis tortor at, mattis odio. Donec viverra odio sit amet urna semper, ut luctus nunc ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras venenatis, nisl ac gravida interdum, sem neque suscipit lacus, vel cursus augue erat vitae purus. Sed porttitor leo turpis, id tristique sem venenatis et. Phasellus sed augue vitae felis scelerisque imperdiet et et justo. Duis posuere et sapien efficitur rutrum. Sed dictum eu tortor in gravida. Nam ultrices dui metus, a malesuada tortor ornare in. Proin varius maximus massa, pretium venenatis mauris eleifend quis. Vestibulum placerat a justo vel cursus. Donec aliquam cursus nunc at pulvinar. Donec maximus sed sapien sit amet consectetur. Suspendisse non nulla in neque ultrices ullamcorper.

Nullam vel nisi congue, fringilla justo id, fringilla orci. Maecenas et sodales nunc. Nunc a cursus dolor, at fringilla quam. Etiam non pellentesque dolor. Maecenas a diam non eros elementum pulvinar sed vel arcu. Praesent et lorem ac ex fringilla pulvinar. Phasellus consequat fermentum ante ac tincidunt. Nam imperdiet arcu eu neque interdum tristique. Vivamus aliquam odio consequat rhoncus interdum. Nam dapibus, lacus a euismod pellentesque, tellus massa elementum felis, sit amet rhoncus justo sem vel lorem. Nunc sit amet nisl tempor, commodo ipsum nec, molestie nisi. In dignissim purus in malesuada consequat. Duis lobortis eros eu aliquet mollis. In quam arcu, condimentum a elementum id, elementum a purus. Aliquam non consectetur leo. Vivamus sodales turpis dolor, vel accumsan enim vehicula vitae.

Nullam quis velit at sem tristique tempus. Nulla fermentum justo ac suscipit pharetra. Curabitur sollicitudin est at imperdiet vulputate. Pellentesque egestas, lectus vitae suscipit gravida, augue mi placerat orci, nec scelerisque lectus ex eu dolor. Pellentesque tempor sed lorem non luctus. Duis in aliquam risus. Proin ac urna mauris. Pellentesque ullamcorper ipsum nulla, vel dignissim nibh venenatis sed. Vestibulum orci nibh, vestibulum sed diam quis, porta lobortis tellus. Morbi a urna in eros ultrices volutpat. Maecenas sed vehicula nibh, a dapibus dui. Sed at scelerisque tellus, at dignissim nulla. Praesent erat lectus, imperdiet ut convallis in, porta vel purus. Aenean condimentum posuere justo, id pretium odio volutpat nec. Mauris bibendum lobortis vulputate. Phasellus sed libero fringilla, ultrices erat et, vulputate purus.

Integer in erat vulputate, elementum odio id, sollicitudin sapien. Donec odio diam, facilisis facilisis interdum in, porta et libero. Nullam quis ultricies dolor, eget vehicula urna. Fusce mi dolor, dignissim eu dignissim ac, eleifend vitae lacus. Donec viverra varius augue. Mauris vitae orci sollicitudin, sollicitudin sem in, blandit mauris. Nullam vel fringilla nibh.

Aenean eu pellentesque lectus. Integer dapibus urna porttitor rutrum sodales. Cras ornare lectus vitae luctus commodo. Nullam in vestibulum velit. Aenean viverra dolor sed venenatis faucibus. Maecenas vel erat urna. Proin ac vulputate massa, sit amet malesuada velit. Vestibulum volutpat nec dolor non tincidunt.

Duis leo urna, euismod sollicitudin ipsum ac, maximus consectetur nibh. Curabitur egestas, orci id eleifend rhoncus, dolor metus pulvinar purus, id vulputate justo lectus vitae mi. Sed libero dui, aliquet vel nunc quis, laoreet feugiat orci. Aenean eu metus nec lacus feugiat rutrum. Duis tempor leo sit amet viverra sodales. Aenean mollis viverra elit fringilla varius. Maecenas ipsum enim, cursus ac aliquet suscipit, semper quis urna. Nullam nec enim non augue venenatis finibus ac nec felis. Morbi tincidunt metus ut lacus molestie convallis.

Sed tincidunt felis quis consectetur maximus. Aliquam erat volutpat. Proin ultrices ipsum eu pulvinar tincidunt. Sed efficitur pharetra euismod. In hac habitasse platea dictumst. Vestibulum ut libero varius augue eleifend euismod. Mauris rhoncus hendrerit libero, ut pellentesque purus finibus quis. Aenean a tortor ullamcorper, lobortis orci vitae, luctus mauris. Integer at purus sed nulla sodales sagittis nec in libero. Curabitur lacinia dignissim est, nec vestibulum nibh vehicula sed. Suspendisse in augue augue. Aliquam id aliquet eros, eget fermentum quam. Aenean id purus id ligula dictum hendrerit a vel ligula. Phasellus facilisis ornare dolor, sit amet tempus mauris vehicula ac.

Fusce sem velit, condimentum vel condimentum ut, facilisis nec felis. Donec vel erat sed est elementum ultrices. Nunc bibendum aliquet massa, non sagittis dolor aliquet vitae. Donec volutpat, dolor vitae lobortis sagittis, diam lorem volutpat nisl, varius vestibulum justo arcu sit amet orci. Curabitur ultrices urna tortor, vitae accumsan libero pretium vitae. Phasellus in nisi egestas, ultrices elit quis, lacinia ligula. Praesent semper, felis et fringilla dapibus, purus sem molestie nulla, sit amet semper turpis metus ac ipsum. In ultrices, est at mattis iaculis, dui ex pharetra ante, sit amet molestie leo lacus vel est. Vestibulum in ipsum vel ante interdum elementum. Sed facilisis ante sit amet faucibus scelerisque. Curabitur consectetur suscipit odio. Curabitur pretium orci ut lacus viverra eleifend.

Cras venenatis nisl nisi, porta aliquam dolor aliquam vel. Nam arcu est, auctor sit amet sodales at, accumsan eget nulla. Sed eu turpis quis dolor iaculis interdum. Phasellus sed odio quis risus facilisis vulputate. Curabitur diam nunc, facilisis ut euismod a, ullamcorper id dolor. Praesent eu quam mauris. Praesent dignissim ex eget erat rhoncus, at luctus ex imperdiet. Aliquam sit amet ex congue, mollis elit laoreet, tincidunt sapien. Cras placerat tortor risus, a ornare magna cursus quis. Sed eu nisl ut tellus faucibus vulputate. Ut sed tempus nisi. Quisque aliquet leo vitae libero sagittis scelerisque.

Maecenas laoreet feugiat rutrum. Aliquam vitae auctor velit, at facilisis lorem. Suspendisse potenti. Aliquam quis tellus vestibulum, molestie lorem eu, consequat elit. Fusce elementum tempor fringilla. Phasellus pretium augue ac elit tempor dapibus. Cras porta et metus vel scelerisque. Pellentesque luctus, neque maximus dictum semper, libero felis pharetra risus, sit amet commodo ligula est quis quam. Integer eleifend, nulla nec pellentesque maximus, leo mauris suscipit nibh, a porta est lectus quis felis. In mattis porta orci, ac ultricies leo tincidunt in. Etiam lacinia mollis urna, vel maximus leo consectetur eu.

Fusce ac aliquam lectus. Vestibulum vitae nunc vitae tellus fermentum malesuada eget sit amet tortor. Nunc hendrerit, quam ut tincidunt elementum, risus dui porttitor diam, facilisis elementum magna neque ac nulla. Fusce massa sem, lacinia non sodales eu, ultricies id orci. Donec ultricies, metus id volutpat dignissim, massa justo interdum metus, ut aliquet sem dui ut nunc. Vivamus at eleifend libero, nec ultricies ligula. Integer laoreet justo ac mauris rutrum interdum. Etiam dignissim lacinia neque, ut mattis tortor ultricies et. Praesent vitae euismod justo, sit amet tincidunt tortor. Vivamus tempor mauris augue.

Morbi feugiat turpis urna, sit amet luctus ligula fermentum non. Morbi convallis eu eros quis maximus. Morbi vulputate tempor sodales. Suspendisse vitae mollis turpis. In accumsan pulvinar neque vel laoreet. Aenean nec lacus erat. Nullam nec egestas odio, sed mollis nisl. Suspendisse velit ex, posuere in ornare at, cursus sed ante. Morbi consectetur orci vel dolor tincidunt, ac volutpat tellus ornare. Nulla malesuada tincidunt felis a mattis. Pellentesque mollis tellus non turpis lacinia fringilla. Mauris a efficitur dui. Curabitur maximus, nunc quis viverra facilisis, sem diam fringilla sem, eu placerat dolor magna non erat. Donec pulvinar erat in suscipit bibendum.

Curabitur et ligula condimentum, maximus nisi at, dapibus leo. Cras imperdiet bibendum pellentesque. Maecenas nec lectus vitae lacus tempus accumsan. Vestibulum eu lorem ultrices, ullamcorper elit non, mollis dolor. Vivamus ac lacinia nunc, at elementum velit. Proin eget facilisis lorem, ut sollicitudin urna. Nunc commodo justo ut pharetra euismod. Suspendisse gravida sem sem, ac cursus elit molestie vel. Fusce porta justo ac neque tempus finibus. Cras et tristique nulla. Etiam ornare, mauris in feugiat laoreet, dui tortor maximus nunc, eu elementum nisl augue ut est. Proin luctus a ante ac fringilla. In hac habitasse platea dictumst. Donec luctus magna tellus, a suscipit est sodales at.

Donec tristique sit amet lectus non pharetra. Duis vel tincidunt mauris. Quisque vestibulum semper arcu, et convallis magna congue at. Suspendisse aliquam eros quis neque consectetur imperdiet. Nam at mauris et diam aliquam fringilla a sit amet sem. Aenean ut ornare justo. In in arcu nunc. Phasellus varius tellus non neque semper dignissim. In cursus pharetra ipsum, ultrices congue tortor ultrices eget. Quisque vitae ante id nulla aliquam mattis vitae a mi. Duis pretium ultrices lorem, a tincidunt risus sollicitudin et. Morbi blandit erat a sem elementum consequat.

Ut accumsan metus ut tellus posuere molestie. Vivamus placerat mollis urna eu posuere. Sed in sapien augue. Curabitur tincidunt urna ut massa ullamcorper vehicula. Pellentesque rutrum tincidunt quam, ac eleifend mi aliquam sit amet. Aenean sit amet cursus eros. Pellentesque a lorem ut urna faucibus sodales eget tristique augue.

Proin tempor massa odio, at cursus erat blandit ut. Nullam leo libero, rutrum non aliquet sed, tincidunt eget odio. Praesent vel metus vel dolor facilisis imperdiet at et nisl. Aenean sagittis eleifend semper. Nulla et cursus mauris, vel tempor dui. Quisque tincidunt auctor rutrum. Morbi elit elit, pretium et nisi vitae, dignissim posuere justo. In id sem non erat facilisis ullamcorper. Pellentesque sed lacus aliquet, pulvinar purus gravida, fermentum est. Nulla rutrum, est eget scelerisque facilisis, lacus ante fermentum ipsum, quis vestibulum arcu lacus a nunc. In scelerisque pretium nisl convallis bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Sed laoreet congue lorem, quis molestie nulla rhoncus nec. Sed fermentum iaculis arcu, quis vulputate sem varius non. Nunc ut facilisis diam, id bibendum metus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras laoreet lectus quis quam elementum, non luctus purus ultrices. Vestibulum laoreet nisi eu venenatis ultricies. Vivamus dictum purus tortor, nec hendrerit erat cursus ut. In euismod nisi sit amet nibh fringilla venenatis.

Morbi nunc enim, finibus vitae libero quis, eleifend laoreet erat. Fusce suscipit efficitur lectus quis rhoncus. Integer et rutrum urna, eget sollicitudin ipsum. Mauris volutpat euismod dui, eget suscipit tortor pharetra in. Maecenas sed tortor et urna gravida pharetra in non mauris. Quisque elementum velit id augue lacinia convallis. Sed eros leo, semper et ornare a, accumsan eu turpis. Quisque dolor turpis, viverra ac orci at, accumsan lobortis orci. Pellentesque ac euismod justo. Praesent semper, eros pretium placerat interdum, lacus elit pellentesque quam, nec viverra risus eros sit amet orci. Aliquam erat volutpat. Nullam tristique auctor vehicula.

Fusce cursus in est non molestie. Morbi vel ipsum pretium ex porttitor malesuada. In placerat purus eget porttitor convallis. Vivamus quis tristique enim, vitae condimentum magna. Nam nec egestas eros, et lacinia nisl. Vestibulum orci dolor, pretium eget pretium eu, cursus sollicitudin justo. Nullam tincidunt velit at bibendum posuere. Suspendisse blandit justo eget diam cursus sagittis. Donec semper ante at justo egestas lacinia. Vivamus a purus eu ipsum consequat dapibus vel eu eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris eget erat bibendum, rutrum ligula vitae, tristique erat. Phasellus consectetur non libero a accumsan. Integer vitae erat purus.

Praesent tempor augue felis, et vehicula dolor porttitor bibendum. Nunc nec posuere mauris. Nam imperdiet risus lorem, ut rhoncus elit convallis a. Vestibulum vitae arcu in risus rutrum laoreet. Vivamus eu sem nisi. Proin sagittis ipsum eu felis cursus faucibus. Proin semper quis felis vitae eleifend. Pellentesque at sem vel eros hendrerit maximus ut sit amet augue. Fusce vel nisi a nulla accumsan porta. Phasellus pharetra elit quam, at gravida sem aliquam at. Aenean et diam vel lacus pretium auctor. Vestibulum blandit, dui at malesuada tincidunt, leo arcu pellentesque tellus, id auctor lectus tellus sed leo. Pellentesque suscipit aliquam sollicitudin. Duis eget commodo orci, a blandit sem. Nam scelerisque pretium nisl, at malesuada orci hendrerit id. Vivamus porttitor ut magna vel tristique.

Curabitur pellentesque magna eget mollis pretium. Phasellus ut ante rutrum, euismod nisl at, laoreet diam. Sed et venenatis ex. Nunc maximus condimentum odio, ut venenatis nunc. Suspendisse potenti. Maecenas iaculis viverra dolor at suscipit. Suspendisse scelerisque felis vitae ipsum fermentum consequat. Donec vulputate odio blandit, venenatis nunc ac, eleifend enim. Quisque mollis bibendum ipsum, in fermentum nulla fermentum ut. Nunc ultricies orci id ipsum semper, at luctus ipsum ultrices. Quisque nisl quam, varius lacinia accumsan ut, venenatis et nisi.

Mauris vestibulum aliquet arcu, eget rutrum felis luctus sed. Nunc molestie tortor accumsan purus accumsan tristique. Donec lorem lorem, finibus nec porta et, viverra at felis. Ut imperdiet, nibh non luctus scelerisque, lacus metus aliquam turpis, at condimentum urna risus eu est. Cras malesuada tempor lectus ac mollis. Nam vehicula pretium ante quis aliquam. Vivamus eros odio, vulputate eget aliquam quis, tincidunt nec ipsum. Maecenas laoreet malesuada purus, non pharetra ipsum fringilla quis. Integer iaculis, sapien sit amet mattis pulvinar, sapien felis congue velit, sit amet auctor dui nunc ac arcu. Duis pellentesque felis ut sapien gravida placerat. Curabitur odio nunc, mollis eu fringilla id, mattis blandit lacus. Aenean et arcu consequat, molestie augue sed, aliquam metus. Suspendisse et eros felis.

Duis viverra, turpis in imperdiet tempus, orci nisi auctor tortor, ac tristique dui nisl eget odio. Maecenas mattis aliquam aliquam. Proin nec ultrices augue. Nulla blandit sed turpis nec lacinia. Cras tellus lectus, interdum quis consectetur quis, fermentum in odio. Nulla congue mi sem, aliquam vulputate massa vestibulum ut. Quisque eget massa aliquet diam egestas rhoncus. Duis nisi turpis, vehicula ac ex ac, sodales sagittis sem. Quisque elementum, arcu sagittis viverra elementum, odio elit elementum turpis, in cursus magna augue non lorem. Aliquam efficitur nulla a nunc placerat tincidunt. Sed varius vehicula lectus at sodales. Cras ligula lectus, aliquam eu efficitur quis, suscipit sit amet eros. Etiam in leo urna. Fusce posuere felis non justo mattis, vel imperdiet ligula porta. Aenean nulla enim, condimentum eget velit vitae, egestas consequat tellus. Phasellus mattis ipsum in sollicitudin varius.

Curabitur consectetur, eros eu sagittis facilisis, ipsum justo vestibulum elit, ac sollicitudin eros lorem sit amet justo. In varius lorem erat, eget iaculis leo aliquet ut. Duis ac ultrices augue, eu scelerisque tellus. Etiam id pellentesque metus. Aenean volutpat, ipsum et efficitur faucibus, sapien libero dapibus erat, vel auctor lacus eros nec augue. Curabitur venenatis justo ac nisi ultrices luctus. Donec id blandit felis. Nam dignissim, nulla ullamcorper commodo pharetra, erat orci laoreet dolor, at dictum erat purus in lacus. In sollicitudin risus nec magna consectetur pretium. Donec non vehicula metus. Ut sem turpis, bibendum sed risus ac, bibendum dapibus massa.

Aliquam sollicitudin arcu vel enim ullamcorper mollis. Curabitur in aliquam libero. Curabitur rhoncus sapien in arcu vestibulum, ac euismod quam maximus. Aliquam viverra sapien malesuada ante dictum, sed tempus mi fermentum. Vestibulum venenatis convallis vestibulum. Sed vitae euismod ex. Morbi a malesuada risus. Nullam a lorem dignissim, accumsan metus at, sodales erat. Curabitur et neque a nibh posuere ultricies non nec risus. Sed fringilla sagittis viverra. Vestibulum faucibus ante sit amet bibendum porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus feugiat, nunc vitae ullamcorper aliquam, libero odio interdum purus, ut bibendum ante massa ut mauris. Donec arcu tellus, auctor in quam vel, eleifend ultrices est. Duis mattis, elit a convallis hendrerit, urna erat aliquet justo, ac rhoncus sem lorem vel sem. Morbi quam dolor, semper vitae euismod a, mollis vitae lorem.

Fusce et maximus orci. Proin ut volutpat est, in condimentum tellus. Maecenas pellentesque porttitor nunc vitae scelerisque. Proin nunc lorem, viverra nec mollis in, volutpat ac arcu. Quisque cursus velit sapien, eu malesuada est facilisis sit amet. Proin eu magna vestibulum magna maximus aliquet. Fusce est nunc, fringilla non placerat vitae, blandit iaculis nibh. Sed a velit blandit augue posuere blandit.

Ut interdum rutrum dui eget pulvinar. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce sed est eu ipsum ornare pulvinar. Fusce non sem et risus iaculis elementum. Vestibulum vel felis sed velit blandit vulputate et eget tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis tincidunt augue a faucibus facilisis. Suspendisse pharetra pretium urna, a pretium ligula viverra ac. Sed fermentum augue eu augue tincidunt bibendum. Quisque sagittis consectetur egestas. Maecenas bibendum nunc a feugiat porta. Nullam metus eros, lacinia vitae eleifend eget, vulputate id quam. Nulla porttitor id tellus a commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed varius fringilla magna non eleifend. In facilisis risus non nulla viverra malesuada.

Ut finibus arcu sed luctus maximus. Fusce tortor sem, vehicula at commodo sed, condimentum id diam. Ut id blandit mi. Integer iaculis augue nec dignissim ornare. Praesent semper elit augue, vitae pellentesque risus congue ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas luctus nisl posuere quam congue, eget mattis dui laoreet. Cras aliquet viverra ultricies. Vivamus pretium nisl sit amet dolor mollis aliquam. Aenean rhoncus mi et libero molestie, eget mattis felis molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Sed mollis, nisl at porttitor pretium, nisi magna porttitor dolor, sed tempus enim orci quis massa. Nunc eleifend risus vitae faucibus vulputate. Vestibulum convallis dignissim mauris, vitae placerat enim hendrerit eget. Duis pretium dui a augue hendrerit, a hendrerit magna condimentum. Aenean id elit vel dolor consequat accumsan. Nam luctus elit neque, nec dignissim mi eleifend porta. Morbi congue metus felis, a accumsan justo convallis nec. Integer sem eros, euismod at sapien in, sollicitudin scelerisque quam. Curabitur aliquam id nisi eget convallis. Cras suscipit velit sit amet nisl congue, sit amet dictum dui cursus. Curabitur congue, metus quis elementum interdum, arcu lacus congue velit, et fringilla dui felis aliquam velit. Quisque at massa in nulla vehicula eleifend sit amet sed ex. Sed nec tortor purus. Nulla velit ligula, condimentum quis lectus eget, malesuada dignissim massa. Sed pulvinar purus vehicula ex sodales, ornare finibus erat luctus. Aenean lobortis pretium posuere.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc in sapien urna. Praesent facilisis ac est a molestie. Aliquam vitae velit a lectus lobortis venenatis. Vestibulum dictum dolor porta, facilisis metus a, lacinia leo. Nam fringilla condimentum leo eu fringilla. Suspendisse accumsan eget ex fermentum consectetur. Aenean nec velit auctor, convallis nunc ac, vestibulum orci. Suspendisse in commodo urna. Nulla luctus ante quis enim feugiat, ut auctor enim dignissim. Aenean ut tellus consectetur, molestie diam ullamcorper, ornare neque.

In ornare aliquam est vel mattis. Donec at dapibus massa, a fermentum nisi. Aenean mollis finibus maximus. Donec a odio urna. Donec ac justo nibh. Sed a aliquam turpis. Donec euismod sed lorem nec lacinia. Maecenas non viverra purus. Donec magna est, congue ac quam et, tincidunt posuere magna. Mauris iaculis finibus dui ac tempor. Donec hendrerit dapibus leo, non congue mauris sodales sit amet.

Ut id nibh id ex finibus facilisis. Ut quis est id odio imperdiet dictum a eget nisl. Nullam eget lacinia ipsum. Pellentesque sit amet imperdiet leo. Nunc nisl elit, finibus at faucibus sed, pharetra nec nunc. Aenean aliquet accumsan metus ac bibendum. Proin pharetra iaculis ex nec malesuada. In felis orci, venenatis non felis id, suscipit viverra lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec molestie nec lorem sit amet fermentum. Quisque eget sem ut ante suscipit tempor eget ac sapien. Quisque facilisis elit vel tortor consequat molestie. In suscipit nulla sed augue efficitur sollicitudin. Donec non felis nisl. In hac habitasse platea dictumst. Pellentesque id libero nunc.

Suspendisse vehicula suscipit odio, at pellentesque tortor malesuada eget. Integer eu sodales mi. Nulla facilisi. Mauris aliquet vestibulum quam et ultrices. Mauris dui sem, semper at auctor vitae, elementum eu arcu. Pellentesque semper eleifend ullamcorper. In fringilla tortor in nulla dapibus gravida. Proin ullamcorper ullamcorper lorem. Nulla bibendum libero a lacus lobortis, ut iaculis orci ultricies.

Integer mattis rutrum lectus, in pulvinar erat elementum eget. Phasellus congue feugiat lectus non mattis. Pellentesque blandit vel ipsum a ultrices. Ut eu aliquam quam, id volutpat orci. Integer tellus nibh, efficitur eget lacus id, viverra blandit nisl. Nam tristique fringilla risus, eget placerat erat blandit ut. Fusce ut sem vel mauris posuere aliquam. Phasellus venenatis tortor non orci consectetur, in aliquet tortor lacinia. Vivamus molestie congue consectetur. Maecenas euismod id diam id placerat. Integer non viverra lectus. Etiam ex ex, varius et neque ac, facilisis molestie nibh.

Sed tempus purus vitae aliquet placerat. In mollis venenatis lectus, nec ultricies massa blandit quis. Ut est ex, porta vel blandit facilisis, tristique id sem. Curabitur viverra ligula diam, eu fermentum purus porta nec. Duis quis vehicula mauris, et rhoncus neque. Maecenas eu nisi et tortor accumsan lobortis. Phasellus condimentum lacinia orci, nec semper lectus maximus in. Donec ut massa diam. Morbi suscipit dui a pellentesque ullamcorper. Sed sodales rhoncus ligula quis gravida. Integer volutpat ligula sed pharetra rhoncus. Curabitur nisl erat, consequat lobortis interdum at, sodales et justo. Praesent viverra nisl in bibendum ullamcorper. Nam et gravida magna. Quisque commodo convallis sapien, egestas commodo risus faucibus et.

Phasellus id risus eu nisi auctor molestie ac id nisl. Sed ornare orci magna, blandit euismod ipsum elementum vitae. Etiam nec cursus arcu. Nullam vehicula purus quam, vel dictum nisi luctus quis. In iaculis iaculis ultrices. Praesent commodo luctus sem non mattis. Phasellus mollis dui nunc, sagittis convallis ex venenatis quis. Duis massa erat, mattis et vehicula non, ultricies a lectus. Ut finibus elit ut erat interdum, id efficitur diam tristique. Curabitur lacinia pharetra ultricies. Nam ac orci cursus, tincidunt quam sed, laoreet dolor. Donec id leo convallis, luctus sapien sed, blandit nisi. Vivamus at dui lorem.

Sed interdum hendrerit urna nec eleifend. Sed egestas orci sit amet massa suscipit ultrices. Praesent tincidunt vestibulum diam eu vulputate. Aliquam vel nulla non augue pulvinar elementum. Maecenas ac metus tempus, lacinia enim a, tincidunt enim. Maecenas varius felis nisi, at sollicitudin ipsum congue eu. Quisque elementum, urna ut dignissim tempus, leo leo vehicula lorem, pharetra auctor augue tortor quis nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce pellentesque massa id orci aliquet viverra. Vestibulum sodales erat at lobortis auctor.

Etiam nulla magna, tempus eu dapibus quis, interdum vitae nibh. Maecenas fermentum pulvinar laoreet. Suspendisse ut magna purus. Proin pulvinar turpis a magna lobortis, ut finibus lorem posuere. Morbi tristique libero eu dolor consectetur blandit et a ex. Suspendisse sapien nibh, lobortis vitae feugiat eu, posuere sed augue. Donec id magna justo. Ut ultricies massa ac porttitor elementum. Etiam imperdiet risus non est venenatis placerat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec fringilla, diam et fermentum blandit, est ipsum aliquet ante, in luctus mi urna vel felis.

Sed sollicitudin eros vel nunc convallis, nec ullamcorper nisi feugiat. Pellentesque vitae lacinia arcu, vel auctor urna. Cras ultricies turpis felis, ac maximus mi fringilla vitae. Phasellus non dapibus mauris. Aliquam pharetra pellentesque maximus. In sagittis in mauris a commodo. In hac habitasse platea dictumst. Nam consequat, massa ac commodo tincidunt, nisi felis semper turpis, non aliquet nisl quam sit amet purus. Sed ullamcorper ipsum quis ante posuere, ut tincidunt sapien semper. Nam hendrerit urna id purus tristique, interdum accumsan neque commodo. Aenean sed accumsan ante, sit amet consequat odio.

Praesent sed posuere tellus. Vivamus lobortis neque nec orci viverra, sed fringilla augue rutrum. Vestibulum eu nibh ut ante pulvinar mattis sit amet a lectus. Sed pharetra in sem at mollis. Nulla nec est sed lorem fringilla ultrices. Donec molestie massa ut velit pretium, a tempus felis faucibus. Maecenas tempus mauris ut congue luctus. Integer malesuada nisl eget vehicula suscipit. Ut rhoncus libero ex, ut tempor ex ullamcorper eu. Quisque eget ullamcorper orci. Nunc arcu purus, porttitor a ipsum in, rutrum sagittis purus. Curabitur consectetur ex id enim porttitor, eu gravida turpis ultricies.

Proin accumsan nibh et tellus sagittis viverra. Praesent tempor, lectus fermentum auctor ultricies, enim lectus hendrerit nisi, ac malesuada nulla odio vitae dui. Aenean faucibus sollicitudin enim. Nunc sit amet feugiat nunc, in egestas magna. Phasellus quis leo suscipit, ultrices ligula non, gravida felis. Donec ex sem, interdum sed mauris in, varius condimentum enim. Nulla aliquet auctor est, non sodales odio dapibus varius.

Praesent condimentum dui orci, non faucibus nisl accumsan quis. Ut ex neque, dictum ut pretium scelerisque, varius sed elit. Sed non felis vitae lorem egestas malesuada et sit amet nunc. Mauris id condimentum nulla. Integer ornare, neque sed fringilla lacinia, enim odio porttitor enim, eu vestibulum sapien massa a turpis. Nulla mauris magna, fermentum sit amet dui eu, scelerisque porttitor metus. Donec accumsan laoreet tellus, vel sodales eros posuere vitae. Proin faucibus, arcu ut finibus ultricies, magna mi semper magna, quis suscipit mi turpis nec est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas lobortis a quam et scelerisque.

Curabitur sit amet aliquet mi. Quisque non mauris in tellus vulputate faucibus. Integer ut turpis efficitur, placerat ligula in, cursus eros. Maecenas laoreet lacus quis nisi vehicula condimentum. Cras vel sapien dictum diam pellentesque accumsan. Pellentesque imperdiet gravida nisl vitae tincidunt. Curabitur consequat velit at mauris tincidunt blandit. Phasellus efficitur elit ut nibh vestibulum, at vestibulum massa suscipit. Fusce in consequat massa. Vivamus sed diam varius, condimentum nulla sit amet, euismod odio. Nulla a est placerat, pharetra felis et, pellentesque dolor. Sed placerat volutpat dolor, non egestas turpis. Aenean malesuada feugiat nisl. Duis at enim vel risus dignissim vehicula.

Nunc fringilla orci magna, a condimentum nunc luctus in. Nam viverra aliquam ipsum id hendrerit. Donec auctor scelerisque magna, ut blandit orci blandit et. Mauris quis neque eu turpis volutpat efficitur. Nulla congue rutrum risus facilisis tristique. Nunc viverra accumsan faucibus. In volutpat commodo enim ut vestibulum.

Maecenas sed mauris maximus, rutrum justo eget, tempus sem. Fusce sit amet sapien non dolor sagittis pellentesque eget id erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur porttitor augue non mi ultrices, sit amet condimentum nunc tristique. Phasellus massa felis, consequat a porttitor sit amet, porttitor congue felis. Nam faucibus, dolor dictum venenatis faucibus, dolor orci aliquet orci, tempus tristique neque dui sit amet nunc. Maecenas et eros vitae libero pretium suscipit nec quis metus. Fusce at porta mi. Mauris eleifend feugiat vehicula.

Vestibulum a urna nulla. Quisque posuere aliquam elit ac viverra. Donec congue tempor erat a imperdiet. Quisque nec quam sed eros pulvinar hendrerit. Mauris et sodales nunc. Sed sit amet dignissim arcu. Etiam laoreet scelerisque posuere.

Cras eu euismod mi. Etiam vel risus sit amet nisi facilisis pellentesque. Nam et turpis mi. In ac urna justo. Pellentesque lacinia volutpat lectus gravida convallis. Mauris pharetra tristique ex, non gravida felis placerat quis. Mauris ipsum nibh, ullamcorper lobortis metus eu, sagittis gravida turpis. Proin malesuada lectus vel nulla lobortis, ac imperdiet nulla eleifend. Praesent eget leo imperdiet, tempor lorem eu, imperdiet lectus. Sed pulvinar diam quam, at viverra magna mollis eget. Donec nisl ex, ullamcorper cursus gravida in, viverra et elit. Suspendisse potenti. Donec sit amet ex et risus sodales ullamcorper scelerisque nec libero.</p>
        </div>
    </>
  )
}
